# This action builds the alpha version as apk on a password protected zip,
# and uploads it to the alpha release.
# Adapted from https://github.com/amirisback/automated-build-android-app-with-github-action
name: Build alpha apk

on:
  # Triggers the workflow on push events for the master branch
  # push:
  #   branches:
  #     - master

  # Run this workflow manually from the Actions tab
  workflow_dispatch:

# parameters
env:
  VARIANT: alpha
  TAG: alpha

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get the repository files
        uses: actions/checkout@v3

      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Set gradlew as executable
        # for some reason the gradle-build-action doesn't do this automatically
        run: chmod +x ./gradlew

      - name: Build & assemble with gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: >
            build
            assemble${{ env.VARIANT }}

      - name: ${{ env.VARIANT }} apk
        # just remove the password here if you want to build the apk yourself
        run: zip -j -P app/build/outputs/apk/app-$.apk

      - name: Update ${{ env.TAG }} tag to current commit
        # equivalent to EndBug/latest-tag@latest but simpler
        run: |
          git tag --force ${{ env.TAG }}
          git push --force origin tag ${{ env.TAG }}

      - name: Upload to ${{ env.TAG }} release
        # equivalent to softprops/action-gh-release@v1 but using official cli
        run: |
          gh release upload ${{ env.TAG }} --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
