# This action checks that the store files are valid for Play Store. Current checks:
# - title and description files must not exceed a maximum number of characters
# To be replaced with a more powerful (and less manual) one
# 
# Made by TrianguloY
name: Validate Triple-T store files
# use it on your own project: https://github.com/TrianguloY/action-validate-Triple-T

on:
  # run this workflow on master branch push
  push:
    branches:
      - master
  # run this workflow on master pull requests
  pull_request:
    branches:
      - master

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Download project files
        uses: actions/checkout@v3

      - name: Validate Triple-T files
        uses: TrianguloY/action-validate-Triple-T@v1
        with:
          appFolder: 'app/standard/, fastlane/metadata/android/'
          ignore: 'Changelog too large'
